import { execFileSync } from "node:child_process";
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { expect, test } from "vitest";

test("packed CLI and native artifacts identify their source repository for provenance", () => {
  const root = mkdtempSync(join(tmpdir(), "openphoto-pack-test-"));
  const repository = { type: "git", url: "https://github.com/example/photo.git" };
  const packages = [
    { directory: "apps/cli", name: "@dzhng/openphoto", main: "dist/bin.js" },
    {
      directory: "packages/img-linux-x64-gnu",
      name: "@dzhng/openphoto-img-linux-x64-gnu",
      main: "image.node",
    },
    {
      directory: "packages/mac-helper-linux-x64",
      name: "@dzhng/openphoto-mac-helper-linux-x64",
      main: "helper",
    },
  ];
  function write(path: string, content: string) {
    const destination = join(root, path);
    mkdirSync(resolve(destination, ".."), { recursive: true });
    writeFileSync(destination, content);
  }
  try {
    write("package.json", JSON.stringify({ version: "1.2.3", repository }));
    write("scripts/.keep", "");
    cpSync(resolve("scripts/sync-versions.mjs"), join(root, "scripts/sync-versions.mjs"));
    write(
      "helpers/mac/Sources/photoctl-mac/ReleaseVersion.swift",
      '// Generated by scripts/sync-versions.mjs from the root release version.\nlet releaseVersion = "1.2.3"\n',
    );
    for (const { directory, name, main } of packages) {
      write(
        `${directory}/package.json`,
        JSON.stringify({ name, version: "1.2.3", main, os: ["linux"], files: [main] }),
      );
      write(`${directory}/${main}`, "fixture bytes");
    }
    write(
      "packages/img-private/package.json",
      JSON.stringify({
        name: "@dzhng/openphoto-img-private",
        version: "1.2.3",
        private: true,
        main: "unbuilt.node",
      }),
    );
    for (const path of [
      "crates/libraw-sys/vendor/LICENSE.CDDL",
      "crates/photoctl-image/NOTICE",
      "crates/photoctl-image/src/highlight.rs",
    ])
      write(path, "fixture notice");
    execFileSync(process.execPath, [resolve("scripts/pack.mjs"), "--all"], {
      cwd: root,
      stdio: "pipe",
    });
    for (const { directory, name } of packages) {
      const tarball = join(root, "out/packages", `${name.slice(1).replace("/", "-")}-1.2.3.tgz`);
      const manifest = JSON.parse(
        execFileSync("tar", ["-xOf", tarball, "package/package.json"], { encoding: "utf8" }),
      );
      expect(manifest.repository, name).toEqual({ ...repository, directory });
      expect(
        JSON.parse(readFileSync(join(root, directory, "package.json"), "utf8")),
      ).not.toHaveProperty("repository");
    }
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}, 30_000);
